# Generated by Django 5.1.5 on 2025-02-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('color', models.CharField(default='#ffa801', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('prio', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('todo', 'Todo'), ('progress', 'In progress'), ('feedback', 'Await feedback'), ('done', 'Done')], default='todo', max_length=8)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(related_name='tasks', to='join_app.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Subtask Title')),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=4, verbose_name='Status')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_app.task', verbose_name='Parent Task')),
            ],
        ),
    ]
