# Generated by Django 5.1.5 on 2025-02-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
