# Generated by Django 5.1.5 on 2025-02-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_alter_contact_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
