# Generated by Django 5.1.5 on 2025-02-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
