# Generated by Django 5.1.5 on 2025-02-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
