# Generated by Django 5.1.5 on 2025-01-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_subtask_rename_contacts_contact_delete_subtasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(related_name='tasks', to='join.contact'),
        ),
    ]
