# Generated by Django 5.1.5 on 2025-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_rename_type_task_category_task_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=4),
        ),
    ]
