# Generated by Django 5.1.5 on 2025-02-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_subtask_created_at_subtask_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='updated_at',
        ),
    ]
