# Generated by Django 5.1.5 on 2025-02-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_remove_subtask_created_at_remove_subtask_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
