# Generated by Django 5.1.5 on 2025-02-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0009_task_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
