# Generated by Django 5.1.5 on 2025-02-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0010_alter_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(default='#ffa801', max_length=7),
        ),
    ]
