# Generated by Django 5.1.5 on 2025-01-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_subtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('todo', 'Todo'), ('progress', 'In progress'), ('feedback', 'Await feedback'), ('done', 'Done')], default='todo', max_length=8),
        ),
    ]
